"""Adding unique constraint to skill_name attre in skill model

Revision ID: 321d66d4fe5b
Revises: 99aed21514cf
Create Date: 2024-05-03 16:38:50.806519

"""
from typing import Sequence
from typing import Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "321d66d4fe5b"
down_revision: Union[str, None] = "99aed21514cf"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "skills", ["skill_name"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "skills", type_="unique")
    # ### end Alembic commands ###
