"""Adding role attr to users models, and removing the superuser attr, also adding cascade definition in skills and users models

Revision ID: a297652566ae
Revises: 321d66d4fe5b
Create Date: 2024-06-05 15:31:53.548062

"""
from typing import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "a297652566ae"
down_revision: Union[str, None] = "321d66d4fe5b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    userroles = sa.Enum("ADMIN", "MODERATOR", "BASE_USER", "GUEST", name="userroles")
    userroles.create(op.get_bind())

    op.add_column("users", sa.Column("role", userroles, server_default="BASE_USER", nullable=False))
    op.drop_column("users", "is_superuser")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column("is_superuser", sa.BOOLEAN(), server_default=sa.text("false"), autoincrement=False, nullable=False),
    )
    op.drop_column("users", "role")
    # ### end Alembic commands ###
