from enum import Enum


class SkillLevel(str, Enum):
    BEGINNER = "Beginner"
    INTERMEDIATE = "Intermediate"
    ADVANCED = "Advanced"


class CategoryOptions(str, Enum):
    GENERAL = "General"
    ENGINEERING = "Engineering"
    WEB = "Web Development"
    MOBILE = "Mobile Development"
    UX_UI = "UX/UI Design"
    GAME = "Game Development"
    BIG_DATA = "Big Data"
    ANALYTICS = "Analytics"
    CYBERSECURITY = "Cybersecurity"
    ROBOTICS = "Robotics"
    EMBEDDED_SYSTEMS = "Embedded Systems"
    AUGMENTED_REALITY = "Augmented Reality"
    VIRTUAL_REALITY = "Virtual Reality"
    BLOCKCHAIN = "Blockchain"
    AUTOMATION = "Automation"
    DATA_SCIENCE = "Data Science"
    SOFTWARE_ARCHITECTURE = "Software Architecture"
    MACHINE_LEARNING = "Machine Learning"
    IOT = "Internet of Things"
    PROGRAMMING = "Programming"
    DEVOPS = "DevOps"
    IT = "Information Technology"
    VETERINARY_MEDICINE = "Veterinary Medicine"
    CLOUD_COMPUTING = "Cloud Computing"
    AI = "Artificial Intelligence"
    DB = "Database"
    SECURITY = "Information Security"
    NETWORKING = "Computer Networking"
    COMPUTER_VISION = "Computer Vision"
    IMAGE_PROCESSING = "Image Processing"
    NATURAL_LANGUAGE_PROCESSING = "Natural Language Processing"
    FINTECH = "Financial Technology"
    HEALTHCARE_TECHNOLOGY = "Healthcare Technology"
    BIOINFORMATICS = "Bioinformatics"
    SPACE_TECHNOLOGY = "Space Technology"
    NANOTECHNOLOGY = "Nanotechnology"
    RENEWABLE_ENERGY = "Renewable Energy"
    AEROSPACE_ENGINEERING = "Aerospace Engineering"
    MATERIALS_SCIENCE = "Materials Science"
    QUANTUM_COMPUTING = "Quantum Computing"
    REAL_ESTATE = "Real Estate"
    ADVERTISING = "Advertising"
    TRAFFIC_MANAGEMENT = "Traffic Management"


class UserRoles(str, Enum):
    ADMIN = "ADMIN"
    MODERATOR = "MODERATOR"
    BASE_USER = "BASE_USER"
    GUEST = "GUEST"
